---
title: "Day4_Hexagons"
author: "Chen-Chia Ku"
date: "2024-11-02"
output: html_document
editor_options: 
  chunk_output_type: console
---
# setwd
```{r}
setwd("E:/Drive/6_Rworld/30DayMapChallenge")
```

# library
```{r}
library(raster)
library(ggplot2)
library(dplyr)
library(hexbin)# install.packages("hexbin")
library(ggpubr)
library(ggnewscale)
library(sf)

```

# 1. Get the data from Climate AP
## Need DEM data
```{r}

taiwan_DEM <- raster("./MapDt/TaiwanMapDEM/tif file/twdtm_asterV2_30m.tif" )
```

## compile the data into a 30 x 30 m 
```{r}
DEM_aggr <- aggregate(taiwan_DEM, fact=10)
Tai_DEM <- rasterToPoints(DEM_aggr)
Tai_DEM2 <- as.data.frame(Tai_DEM) %>%
  rename(elevation='Layer_1')
```
Note that, after this chunk, the data will go to Climate AP to output the long-term data for each grid from the DEM data.
The out put data will be inputed in the following data input. 


# Data input
```{r}
#1991-2020 data from Climate AP

Rain <- read.csv("./2024_Challenge/Process/Day4_Hexagon/Tai_DEM2_Normal_1991_2020Y.csv")
Ocean_DEM <- raster("./MapDt/TaiwanOCean/gebco_2023_n27.0_s20.0_w116.0_e125.0.tif")
```

# Data compiling
## Ocena Data
```{r}
Ocean_aggr <- aggregate(Ocean_DEM, fact=5)
Ocean_DEM1 <- rasterToPoints(Ocean_aggr)
Ocean_DEM2 <- as.data.frame(Ocean_DEM1) %>%
  rename(elevation='gebco_2023_n27.0_s20.0_w116.0_e125.0')

```

## Precipitation Data
```{r}
Rain2 <- Rain %>%
  mutate(MAP=ifelse(MAP==-9999, NA, MAP)) %>%
  filter(!(Longitude < 120 & Latitude > 24.5))
```

# Map
```{r}
TopoPal <- colorRampPalette(c("#f1ede7","grey60","grey30" ))
mypal <- colorRampPalette(c("#FFFFFF","#184a76","#0f2f4c" ))

Precipitation_Hex <- ggplot()+
  #geom_sf(data=Taiwan_Union ,fill="#D8EFE5", colour="#0F381D", alpha=0)+
  geom_tile(data=Ocean_DEM2, mapping=aes(x=x, y=y, fill=elevation))+
  scale_fill_gradientn(colours = TopoPal(20))+
  new_scale("fill") +
  
  stat_summary_hex(Rain2, mapping=aes(x=Longitude, y=Latitude,z = MAP,
                                      fill = after_stat(..value..),
                                      colour = after_stat(..value..)),
                   bins=200, alpha=0.6)+
  scale_fill_gradientn(name="Precipitation (mm)", colours = mypal(20))+
  scale_colour_gradientn(colours = mypal(20))+
  
  
  #geom_sf_text(data=taiwan_shp,mapping = aes(label=NAME_2), size=2) +
  
  coord_sf(xlim = c(119.2, 122.6), ylim = c(21.8, 25.8),crs=4326)+
  theme(panel.background = element_rect(fill = "transparent", ), 
        panel.grid = element_blank(), 
        plot.margin = margin(0, 0, 0, 0, "cm"),
        axis.text.x = element_text(vjust = 15, size=5, color="#0F381D"),
        axis.text.y = element_text(angle = 270, vjust = 15, hjust=0.5, size=5, color="#0F381D"),
        axis.ticks = element_blank(),
        axis.title = element_blank(), 
        legend.position = "none")

Precipitation_Hex

```

```{r}
ggexport(Precipitation_Hex, filename = "Precipitation_Hex2.png", width = 7200, height=9000, res=800)


```
